### ISSUE TITLE
Feature request: sex chromosome CNV calling

### ISSUE THREAD

**Issue by dthung** [ccagc/QDNAseq#10] opened 2015-03-31 09:20 UTC
Dear authors,

Thanks for sharing your very nice package with the community, it seems to work well on our data. I am wondering whether you have plans for incorporating support for the sex chromosomes, as it currently seems that QDNseq does not handle these chromosomes properly. We would be very much interested in such a feature.

**Comment by ilarischeinin** [comment] 2015-03-31 14:58
Which version are you using?

I'm assuming that you are referring to the `applyFilters()` function, which filters out some of the bins. QDNAseq has five separate filters, and each one can be turned on/off using parameters:
* `residual`: remove bins based on the 1000 Genomes data and loess residuals described in the paper (on by default)
* `blacklist`: remove bins in ENCODE's blacklist (on by default)
* `mappability`: remove bins with mappabilities lower than a given threshold (off by default)
* `bases`: remove bases with more N's in the reference sequence than a given threshold (off by default)
* `chromosomes`: remove specific chromosomes (X and Y by default)

Prior to QDNAseq version 1.2.2, use of the `residual` filter (which is on by default) would always filter out chromosomes X and Y, irrespective of what the `chromosomes` parameter was set to. But since that version, all chromosomes are kept when you do a `applyFilters(object, chromosomes=NA)`.

**Comment by dthung** [comment] 2015-04-01 08:05
Sorry, I think I should have been a little more clear. I'm currently using version 1.2.4 and I was able to use QDNAseq for calling on X and Y, but it altered the calling on the autosomes.

I reran QDNAseq using filtering of X and Y in the **first run**: `applyFilters(readCounts, residual = TRUE, blacklist=TRUE, chromosomes=c("X", "Y"))` and without filtering of X and Y in the **second run**: `applyFilters(readCounts, residual = TRUE, blacklist=TRUE, chromosomes=NA)` as you suggested on the same sample and same background set.

This however resulted in a difference between the calling on the autosomes. For instance in the lower plot (without filtering on X and Y) the deletion has a much smaller probability, an additional gain is called and the rest of the chromosome has a very low deletion probability.

![qdnaseq_chr10_excludingxy](https://cloud.githubusercontent.com/assets/6398209/6936583/2d41d4cc-d854-11e4-8570-068b2d919182.png)
![qdnaseq_chr10_includingxy](https://cloud.githubusercontent.com/assets/6398209/6936585/3368fc86-d854-11e4-853d-89fad4da8651.png)

Is there a way to correct for these discrepancies when not filtering on X and Y?

**Comment by daoud-sie** [comment] 2015-04-01 13:10
Thanx for your clarity. Currently the gc/mappability correction does not support the X and Y chromosome. Fix is underway.

**Comment by ilarischeinin** [comment] 2015-04-01 18:04
OK, thanks, now I understand. There's a few different things in this post, so bear with me. *Text in italics* is mainly meant for other developers, so dthung feel free to skip over them. And if you want to just know what works for now, jump to "What works", which gives you two options.

##### Issue 1. What to estimate the GC/mappability correction from

Function `estimateCorrection()` calculates the loess fit based on the set of bins that is currently set to be used via the `applyFilters()`. So, when one includes the sex chromosomes, they too are used to estimate the correction. And since the copy number is not the "normal" 2, using the X chromosome throws the correction off for males, and using Y does so for both genders. This is the difference you are seeing.

A solution to this is to not use X and Y when estimating the correction, but to include them after this step:

```r
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts)
readCounts <- applyFilters(readCounts, chromosomes=NA)
copyNumbers <- correctBins(readCounts)
```

*One can of course argue that `estimateCorrection()` should always ignore X and Y, but I think there are a few different sides to this coin. If it is hard-coded inside the function, what if a user has an all-female data set, and would actually like to use X for the correction? And if both `applyFilters()` and `estimateCorrection()` functions includ an argument `chromosomes` defaulting to `c("X", "Y")`, I think this could be a possible source for confusion for a user who thought they did something, but didn't realize they needed to do the same thing in two different ways. That's why I think giving the control to the user and respecting their choice is the most straightforward approach here. But what would make sense is first of all to include some instructions on how to also use X/Y in the documentation, and also to make `estimateCorrection()` issue a warning when X/Y are included. That would allow people to do whatever they wanted, but also to notice it if they were doing it by accident. And last but not least, whatever we do here does not solve the second issue:*

##### Issue 2. Combinations of GC and mappability

In total, there are 2,720 different combinations of GC and mappability in the genome (when GC and mappability are rounded to integers). Not all of these are necessarily present in the bins that `estimateCorrection()` uses to make the loess fit, but it interpolates the missing ones. However, the problem is that it only interpolates and does not extrapolate (this is default behavior of `loess()`). This means that edge cases sitting at the edge of the GC/mappability pane cannot be corrected, and will end up with missing values (which cause problems in subsequent steps).

When running the commands listed above, there are 501 bins (164 in X, 337 in Y) such bins. There's a couple of ways to deal with this:

##### What works at the moment

The first option is to manually exclude those problematic bins:

```r
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts)
readCounts <- applyFilters(readCounts, chromosomes=NA)
fData(readCounts)$use <- fData(readCounts)$use &
  !is.na(rowMeans(assayDataElement(readCounts, "fit")))
copyNumbers <- correctBins(readCounts)
```

The second option is to make `loess()` allow extrapolation. This could potentially affect the correction applied to "regular" bins as well, and has not really been evaluated.

```
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts,
  control=loess.control(surface="direct"))
readCounts <- applyFilters(readCounts, chromosomes=NA)
copyNumbers <- correctBins(readCounts)
```

A third option could also be to use some kind of imputation to get rid of the missing values.

##### Issue 3: Lack of residual filter

Not exactly in the same boat as the previous two, but since X and Y cannot use the `residual` filter, they are more noisy than other chromosomes and therefore give lower quality data. Because of that, i'd first of all recommend using option `transformFun="sqrt"` for `segmentBins()`, and in general to take the results with a slight grain of salt.

##### *My suggestions going forward with these issues*

*1. add information to vignette and manual pages on how to work with X and Y, and also to update `estimateCorrection` to issue that warning (I could take care of these)
2. `correctBins()` could automatically filter out the bins with missing values, i.e. the first solution above (I could implement this), in addition/instead of this, the use of extrapolation could be evaluated (by someone else than me)
3. could also look into implementing a `residual` filter also for X, maybe even Y (someone else)*

**Comment by dthung** [comment] 2015-04-02 15:39
Thank you for the very thorough explanation of the different issues, it is very insightful.

I tried both of the workarounds (1: excluding problematic bins and 2: allow `loess()` to do extrapolation.

However the calling and deletion / gain probabilities still seem off.

For instance the same chr10 plot of the same sample with a clear deletion in it using **option 1** (excluding problematic bins) looks like this:
![qdnaseq_chr10_excludingbins](https://cloud.githubusercontent.com/assets/6398209/6967266/7e60365e-d95e-11e4-9768-47fd0381fee7.png)

And **option2** looks like this:
![qdnaseq_chr10_loess](https://cloud.githubusercontent.com/assets/6398209/6967274/8c3baef2-d95e-11e4-937b-4112ad550b4a.png)

Maybe I made a stupid mistake in integrating the code you provide in your previous comment so here is a basic breakdown of the code used for **option1**:

```{r}
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts)
readCounts <- applyFilters(readCounts, chromosomes=NA)
fData(readCounts)$use <- fData(readCounts)$use & !is.na(rowMeans(assayDataElement(readCounts, "fit")))
copyNumbers <- correctBins(readCounts)


copyNumbersNormalized <- normalizeBins(copyNumbers)
copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt")
copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
copyNumbersCalled <- callBins(copyNumbersSegmented)
```

And here is the breakdown of the code used for **option2**:
```{r}
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts, control=loess.control(surface="direct"))
readCounts <- applyFilters(readCounts, chromosomes=NA)
copyNumbers <- correctBins(readCounts)


copyNumbersNormalized <- normalizeBins(copyNumbers)
copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt")
copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
copyNumbersCalled <- callBins(copyNumbersSegmented)
```

If needed I can also provide the code I use for making the chr10 plot.

**Comment by ilarischeinin** [comment] 2015-04-02 15:52
Your code looks good to me.

Basically what QDNAseq's job really is, is the black dots. It's purpose is to go from what you have if you make a plot right after calling `binReadCounts()` to here (i.e. the filtering and correction steps). And to me the black dots look good and show a very clear loss.

The brown lines are what DNAcopy (QDNAseq's `segmentBins()` function calls package DNAcopy) does (segmentation) and that looks very clear too: the loss is picked up by the segmentation. Did you also try without the `transformFun="sort"` option, maybe that could be better?

And the calls and call probabilities (red and blue bars) come from CGHcall (which QDNAseq's `callBins()` function uses). So, to me, it seems that's where the issue is. Daoud, maybe this is something you could take up with Mark? Maybe it has something to do with the distribution of the data not being as Gaussian as microarray data due to it being derived from counts.

**Comment by daoud-sie** [comment] 2015-04-02 22:02
It looks to me a calling (CGHcall) issue as well. At least we have a workable way of correcting the data with X and Y on board. I will contact Mark van de Wiel and see what he has to say about it. If you don't mind sharing some of your data we can start some troubleshooting. Drop me an e-mail if you can do so. For now I will close this issue as it seems that the remainder of the problem is not to be solved in the QDNAseq code.

**Closed by daoud-sie** 2015-04-02 22:02 UTC

**Comment by jiading** [comment] 2016-05-31 10:30
@dthung 

Could you please provide the code to plot chr10? 
Thanks.

**Comment by dthung** [comment] 2016-05-31 12:19
@jiading 

It's been a long time, so not sure what code I exactly used. Something like below, should come close though (this assumes you have assigned the results of `callBins` to the variable `copyNumbersCalled`):

```R
f.data <- as(featureData(copyNumbersCalled), "data.frame")

#Looping over chromosomes
for (chromosome in c(1:22)){
  select <- which(f.data$chromosome == chromosome)
  print(paste("Plotting chromosome:", chromosome, sep = " "))

#Looping over samples, make a plot per sample, per chromosome
  for (i in 1:ncol(copyNumbersCalled)){
    sample.name <- sampleNames(phenoData(copyNumbersCalled))[i] #You can use this, for plot title or plot name
    plot(copyNumbersCalled[select, i], ylim=c(-2,2))
  }
}
```

**Comment by P4sm** [comment] 2016-12-15 09:59
I still have the same problem although I followed the manual: 
`> readCounts <- binReadCounts(getBinAnnotations(15))`
`> readCounts <- applyFilters(readCounts)`
`> readCounts <- estimateCorrection(readCounts)`
`> readCounts <- applyFilters(readCounts, chromosomes=NA)`
`> copyNumbers <- correctBins(readCounts)`

If i include the sex chromosomes, my non-sex chromosome CNVs change drastically.

**Comment by daoud-sie** [comment] 2016-12-16 00:04
Can you provide some more info on what data you have and what your profiles look like?

**Comment by P4sm** [comment] 2016-12-16 09:49
The whole-genome sequencing data have rather low coverage: ~ 0.5X. Here is an example: First without sex chromosomes and then with sex chromosomes

![screenshot from 2016-12-16 11-38-22](https://cloud.githubusercontent.com/assets/23518979/21258275/e152e380-c384-11e6-8e84-373e03c111b0.png)
![screenshot from 2016-12-16 11-41-07](https://cloud.githubusercontent.com/assets/23518979/21258277/e5140b20-c384-11e6-800f-56d248321905.png)

So chromosome Y has a little reads, but even when I leave it out, the results are just as bad. Here:

![screenshot from 2016-12-16 11-48-34](https://cloud.githubusercontent.com/assets/23518979/21258424/a2c18a8a-c385-11e6-92bd-7f78bc40fc80.png)

**Comment by daoud-sie** [comment] 2016-12-16 10:07
I wouldn’t be so pessimistic. The binning, corrections and filter steps have worked out great and the segmenation too. That is a solid basis. I assume you are disappointed that the smaller gains and losses are no longer being called and that the X chromosome is acting up. However, the calling is being performed by CGHcall which was designed for array data. Also CGHcall can give odd results when you run it with just one sample. Are you running more than one sample through the analysis?

**Comment by drkvnssn** [comment] 2016-12-16 13:27
Daoud... Dit een probleem voor get script dat ik heb geschreven. Lijkt een zeer lage cnv te zitten op x..

Dirk

**Comment by P4sm** [comment] 2016-12-19 07:58
Do you know why chrX is "acting up" like that? I don't see myself deletion there.

**Comment by ilarischeinin** [comment] 2016-12-19 10:27
I don't have an answer, but if CGHcall gives weird results, I would try with `callBins(..., method="cutoff")`. (For cancer samples, some tuning of the default `cutoffs` is most likely required.) Like Daoud said, CGHcall can behave a bit odd if run on individual samples and/or non-cancer samples.

Another thing that might be worth trying is to do the segmentation with `segmentBins(..., transformFun="sqrt")`, and then see if calling improves.

**Comment by drkvnssn** [comment] 2016-12-19 11:40
There is a homozygous deletion (a bin with 0 counts) on x which will pull down the average of the segmentation result - thus calling a ‘deletion’.. I have made a function (adjustBinCount) that will top up all the bins including the 0-bins which will remove the very-very small segments and thus removing the pulling down of the other segments.

maybe you could see if this works..

Dirk

https://github.com/drkvnssn/QDNAseq/blob/adjustBinCount/R/adjustBinCount.R
